admin-bot:
  debug: true
  timeout: 60
  parse_mode: markdown
  
public-bot:
  debug: true
  timeout: 60
  parse_mode: markdown

heroku:
  url: "https://mohyla-cinema-club-bot.herokuapp.com/%s"

redis:
  url: "localhost"