admin-bot:
  debug: false
  timeout: 60
  offset: 0
  parse_mode: markdown
  
public-bot:
  debug: false
  timeout: 60
  offset: 0
  parse_mode: markdown

heroku:
  url: "https://mohyla-cinema-club-bot.herokuapp.com/%s"
