main:
  environment: "prod"
  stage: "test"

admin-bot:
  debug: true
  timeout: 60
  parse_mode: markdown

public-bot:
  debug: true
  timeout: 60
  parse_mode: markdown
  
redis:
  url: "redis-test"
  port: ":6379"
  password: "redis-test"
  db: 0
  ttl: "72h"